config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root "mappings#index"

  resources :webhook_events, only: [:create, :index] do
    member do
      put :reprocess
    end
  end

  resource :customer, only: [:show, :update] do
    member do
      post :revoke_token
      get :ping_api
      get :wizard
    end
  end

  resources :mappings, only: [:index]
  resources :nocrm_steps, module: :mappings
  resources :nocrm_field_types, module: :mappings

  # oauth section for salesforce
  namespace :auth do
    resource :salesforce, controller: :salesforce, only: [:show] do
      collection do
        post :synchronize_fields
        post :revoke_token
      end
    end
    resources :salesforce, only: [] do
      collection do
        get :connect
        get :oauth2callback
        get :authentication
      end
    end
  end
end

app/models/mapping.rb
class Mapping < ApplicationRecord
  acts_as_tenant :customer
  belongs_to :nocrm_object, polymorphic: true
  belongs_to :salesforce_object, polymorphic: true

  validates :salesforce_object_type, format: { with: /SalesforceStage/ }, if: :nocrm_step?
  validates :nocrm_object_type, format: { with: /NocrmStep/ }, if: :salesforce_stage?

  def nocrm_step?
    nocrm_object.is_a? NocrmStep
  end

  def salesforce_stage?
    salesforce_object.is_a? SalesforceStage
  end

  # Getter returning the nocrm_object global_id
  # Used in form & controller
  def nocrm_object_gid
    self.nocrm_object&.to_global_id
  end

  # Setter to allow replacing a nocrm_object for a given global_id value
  # Used in form & controller
  def nocrm_object_gid=(gid)
    self.nocrm_object = GlobalID::Locator.locate(gid)
  end
end

app/controllers/mappings/nocrm_field_types_controller.rb
module Mappings
  class NocrmFieldTypesController < ApplicationController
    before_action :find_mapping, only: [:edit, :update, :destroy]

    def new
      @mapping = Mapping.new
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("remote_modal", partial: "mappings/nocrm_field_types/form_modal", locals: { mapping: @mapping })
        end
        format.html
      end
    end

    def create
      if @mapping = Mapping.create(field_type_params)
        @new_mapped_field = field_type_params['salesforce_object_id']
        respond_to do |format|
          format.turbo_stream
        end
      end
    end

    def edit
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("remote_modal", partial: "mappings/nocrm_field_types/form_modal", locals: { mapping: @mapping })
        end
        format.html
      end
    end

    def update
      if @mapping.update(field_type_params)
        @new_mapped_field = @mapping.salesforce_object.id
        respond_to do |format|
          format.turbo_stream
        end
      end
    end

    def destroy
      @mapping.destroy
      respond_to { |format| format.turbo_stream }
    end

    private

    def field_type_params
      params.require(:mapping).permit(:nocrm_object_gid, :salesforce_object_id, :salesforce_object_type)
    end

    def find_mapping
      @mapping = Mapping.find(params[:id])
    end
  end  
end

app/controllers/mappings/nocrm_steps_controller.rb
module Mappings
  class NocrmStepsController < ApplicationController
    before_action :find_nocrm_step, only: [:update]
  
    def update
      if @step.stage_id = step_params[:stage_id]
        respond_to do |format|
          format.turbo_stream
        end
      end
    end

    private
  
    def step_params
      params.require(:nocrm_step).permit(:stage_id)
    end
  
    def find_nocrm_step
      @step = NocrmStep.find(params[:id])
    end
  end  
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  def index
  end
end

app/views/mappings/nocrm_field_types/_field.html.erb
<div class="py-2" id="<%= dom_id(mapping) %>">
  <div class="d-flex align-items-center card-component clickable px-4 py-2">
    <%= link_to edit_nocrm_field_type_path(mapping), data: { controller: "turbo" }, class: "text-decoration-none text-gray-600 d-flex align-items-center flex-grow-1" do %>
      <div class="form-group w-100">
        <%= "#{mapping.nocrm_object.parent_type}." if mapping.nocrm_object.respond_to?(:parent_type) %><%= mapping.nocrm_object.name %>
      </div>
      <i class="fas fa-arrow-right fa-2x text-gray-200 px-4"></i>
      <div class="form-group w-100">
        <%= mapping.salesforce_object.object_type %>.<%= mapping.salesforce_object.name %>
      </div>
    <% end %>

    <%= button_to nocrm_field_type_path(mapping), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "ps-4 bg-white border-2 border-light border-top-0 border-bottom-0 border-end-0 border-start" do %>
      <i class="fas fa-trash text-red-500"></i>
    <% end %>
  </div>
</div>

app/views/mappings/nocrm_field_types/_field_list.html.erb
<%= turbo_frame_tag "mapped_fields_and_attributes" do %>
  <% nocrm_field_type_mappings = Mapping.where(nocrm_object_type: "NocrmFieldType") %>
  <% nocrm_attributes_mappings = Mapping.where(nocrm_object_type: "NocrmAttribute") %>

  <% if nocrm_field_type_mappings.any? || nocrm_attributes_mappings.any? %>
    <div class="py-2">
      <%= link_to new_nocrm_field_type_path, data: { controller: "turbo" }, class: "btn btn-primary w-100" do %>
        <i class="far fa-plus-circle me-2"></i>
        Add a new mapping
      <% end %>
    </div>
    <%= render partial: "mappings/nocrm_field_types/field", collection: Mapping.where(nocrm_object_type: "NocrmFieldType"), as: :mapping %>
    <%= render partial: "mappings/nocrm_field_types/field", collection: Mapping.where(nocrm_object_type: "NocrmAttribute"), as: :mapping %>
  <% else %>
    <div class="text-center">
      <i class="far fa-network-wired fa-4x text-gray-400"></i>
      <h3 class="mt-4 fs-7 fw-bolder text-gray-900">No mappings</h3>
      <p class="my-2 fs-7 text-gray-500">Make your noCRM fields match your Salesforce ones.</p>
    </div>
    <div class="mt-4 d-flex justify-content-center">
      <%= link_to new_nocrm_field_type_path, data: { controller: "turbo" }, class: "btn btn-primary" do %>
        <i class="far fa-plus-circle me-2"></i>
        Add a new mapping
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/mappings/nocrm_field_types/_form.html.erb
<%= form_with model: mapping, scope: :mapping, url: mapping.persisted? ? nocrm_field_type_path(mapping) : nocrm_field_types_path do |f| %>
  <div class="py-2">
    <div class="d-flex align-items-center mb-3">
      <div class="col-5 text-center">
        <%= image_tag( asset_path("logo.svg"), class: 'w-16' ) %>
      </div>
      <div class="col-2 text-center">
        <i class="fas fa-plus fa-3x text-gray-200 px-4"></i>
      </div>
      <div class="col-5 text-center">
        <%= image_tag( asset_path("salesforce_logo.png"), class: 'w-16' ) %>
      </div>
    </div>
    <p class="mb-5">Whenever you create a lead in our app the noCRM field you pick below will match the Salesforce field you pick from the right selecter.</p>

    <div class="d-flex align-items-center">
      <div class="fw-bold w-100">noCRM Field</div>
      <div class="w-20 px-2"></div>
      <div class="fw-bold w-100">Salesforce Field</div>
    </div>
    <div class="d-flex align-items-center">
      <div class="form-group w-100">
        <% nocrm_fields = NocrmFieldType.grouped_fields_for_select + NocrmAttribute.grouped_fields_for_select %>
        <%= f.select :nocrm_object_gid, options_for_select(nocrm_fields, mapping.nocrm_object_gid),
                     { include_blank: true }, { data: { controller: 'select' } } %>
      </div>
      <i class="fas fa-arrow-right fa-2x text-gray-200 px-4"></i>
      <div class="form-group w-100">
        <%= f.hidden_field :salesforce_object_type, value: 'SalesforceField' %>
        <%= f.select :salesforce_object_id, grouped_options_for_select(SalesforceField.grouped_fields_for_select, selected: mapping.salesforce_object_id, disabled: SalesforceField.mapped.ids.map(&:to_s)),
                     { include_blank: true }, data: { controller: "select" }
        %>

      </div>
    </div>
    <div class="d-flex align-items-center justify-content-end">
      <%= f.submit class: 'btn btn-primary mt-4' %>
    </div>
  </div>
<% end %>

app/views/mappings/nocrm_field_types/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header p-4">
          <h5 class="modal-title fs-4">
            <i class="fas fa-network-wired fa-lg text-blue-800 me-2"></i>
            <%= request.params[:action] = 'new' ? "New mapping" : "Edit mapping" %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body p-4">
          <%= render "mappings/nocrm_field_types/form", mapping: mapping %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/mappings/nocrm_field_types/_live_salesforce_objects.html.erb
<%= turbo_frame_tag "live_salesforce_objects" do %>
  <% SalesforceField::OBJECT_TYPES.each do |object_type, config| %>
    <% required_fields = SalesforceField.send("#{object_type.downcase.pluralize}").where(is_required: true) %>
    <% optional_fields = SalesforceField.send("mapped_#{object_type.downcase.pluralize}").where(is_required: false) %>

    <div class="py-2">
      <div class="shadow-sm bg-white rounded-3 p-4">
        <h3><%= object_type %></h3>
        <% if config[:skip_on_failure] %>
          <div class="text-gray-600 fs-7 fst-italic">
            <i class="fas fa-circle-info text-blue-400 me-1"></i>
            If there is not enough data to create the <%= object_type %>, the Opportunity will still be created
          </div>
        <% end %>
        <div class="row mt-4">
          <%= tag.p "Required fields", class: "text-gray-400 fs-7 mb-0" if required_fields.any? %>
          <% SalesforceField.send("#{object_type.downcase.pluralize}").where(is_required: true).each do |required_field| %>
            <div class="col-4">
              <%= tag.div nil, class: "#{required_field.mappings.any? ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-400' } #{'anim-pulse' if new_mapped_field == required_field.id} rounded-pill px-3 py-1 my-2 text-truncate d-flex align-items-center justify-content-between",
                          data: { controller: "tooltip", tooltip_options_value: { title: required_field.default&.dig(:strategy) || required_field.name } } do %>
                <%= required_field.name %>
                <%= tag.i nil, class: "fas #{required_field.mappings.any? ? 'fa-check-circle text-green-800' : 'fa-asterisk text-red-500' }" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= tag.p "Optional fields", class: "text-gray-400 fs-7 mb-0 mt-4" if optional_fields.any? %>
        <div class="d-flex align-items-center">
          <% SalesforceField.send("mapped_#{object_type.downcase.pluralize}").where(is_required: false).each do |field| %>
            <%= tag.div field.name, class: "#{'anim-pulse' if new_mapped_field == field.id} rounded-pill bg-blue-100 text-blue-800 fs-7 px-3 py-1 my-2 me-2 text-truncate", data: { controller: "tooltip", tooltip_options_value: { title: field.name } } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/mappings/nocrm_field_types/create.turbo_stream.erb
<%= turbo_stream.replace "live_salesforce_objects" do %>
  <%= render partial: "live_salesforce_objects", locals: { new_mapped_field: @new_mapped_field } %>
<% end %>

<% if Mapping.count == 1 %>
  <%= turbo_stream.replace "mapped_fields_and_attributes" do %>
    <%= render partial: "field_list", locals: { mapping: @mapping } %>
  <% end %>
<% else %>
  <%= turbo_stream.append "mapped_fields_and_attributes" do %>
    <%= render partial: "field", locals: { mapping: @mapping} %>
  <% end %>
<% end %>

<%= turbo_stream.replace "remote_modal" do %>
  <%= turbo_frame_tag "remote_modal" %>
<% end %>

app/views/mappings/nocrm_field_types/destroy.turbo_stream.erb
<%= turbo_stream.replace "live_salesforce_objects" do %>
  <%= render partial: "live_salesforce_objects", locals: { new_mapped_field: @new_mapped_field} %>
<% end %>

<%= turbo_stream.remove @mapping %>

<% if Mapping.count.zero? %>
  <%= turbo_stream.replace "mapped_fields_and_attributes" do %>
    <%= render partial: "field_list", locals: { mapping: @mapping} %>
  <% end %>
<% end %>

app/views/mappings/nocrm_field_types/edit.html.erb
<%= render partial: "mappings/nocrm_field_types/form", locals: { mapping: @mapping } %>

app/views/mappings/nocrm_field_types/new.html.erb
<%= render partial: "mappings/nocrm_field_types/form", locals: { mapping: @mapping } %>

app/views/mappings/nocrm_field_types/update.turbo_stream.erb
<%= turbo_stream.replace "live_salesforce_objects" do %>
  <%= render partial: "live_salesforce_objects", locals: { new_mapped_field: @new_mapped_field} %>
<% end %>

<%= turbo_stream.replace dom_id(@mapping) do %>
  <%= render partial: "field", locals: { mapping: @mapping} %>
<% end %>

<%= turbo_stream.replace "remote_modal" do %>
  <%= turbo_frame_tag "remote_modal" %>
<% end %>