config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root "mappings#index"

  resources :webhook_events, only: [:create, :index] do
    member do
      put :reprocess
    end
  end

  resource :customer, only: [:show, :update] do
    member do
      post :revoke_token
      get :ping_api
      get :wizard
    end
  end

  resources :mappings, only: [:index]
  resources :nocrm_steps, module: :mappings
  resources :nocrm_field_types, module: :mappings

  # oauth section for salesforce
  namespace :auth do
    resource :salesforce, controller: :salesforce, only: [:show] do
      collection do
        post :synchronize_fields
        post :revoke_token
      end
    end
    resources :salesforce, only: [] do
      collection do
        get :connect
        get :oauth2callback
        get :authentication
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  with_options dependent: :destroy do |customer|
    customer.has_one :salesforce_account
    customer.has_many :nocrm_steps
    customer.has_many :nocrm_field_types
    customer.has_many :nocrm_attributes
    customer.has_many :nocrm_webhooks
    customer.has_many :salesforce_fields
    customer.has_many :salesforce_stages
  end

  has_secure_token :webhooks_token

  def current_tenant!
    ActsAsTenant.current_tenant = self
  end

  def create_nocrm_attributes
    ActsAsTenant.with_tenant(self) do
      nocrm_att_seed_file = File.join(Rails.root, 'db', 'nocrm_attributes.yml')
      config = YAML::load_file(nocrm_att_seed_file)
      NocrmAttribute.create(config["nocrm_attributes"])
    end
  end

  def has_connected_nocrm?
    nocrm_account.present? && api_key.present?
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    flash.keep
  end

  def update
    if current_customer.update(customer_params)
      NocrmApi.ping_api(current_customer)
      current_tenant.create_nocrm_attributes
      NocrmSyncService.sync_steps(current_customer)
      NocrmSyncService.sync_field_types(current_customer)
      NocrmSyncService.create_webhooks(current_customer)
      redirect_to customer_url, notice: "Your noCRM account is connected."
    else
      redirect_to customer_url, alert: "An error occurred, please check your inputs"
    end
  rescue RestClient::Unauthorized
    current_customer.update(api_key: nil)
    flash[:alert] = "Unauthorized API connection, please check your settings."
    redirect_to action: :show
  rescue URI::InvalidURIError
    current_customer.update(api_key: nil, nocrm_account: nil)
    flash[:alert] = "The noCRM account subdomain is not formatted properly."
    redirect_to action: :show
  end

  def ping_api
    NocrmApi.ping_api(current_customer)
    redirect_to customer_url, notice: "Your API connection is working!"
  rescue RestClient::Unauthorized
    redirect_to customer_url, alert: "Unauthorized API connection, please check your settings."
  end

  def revoke_token
    NocrmSyncService.revoke_token(current_customer)
    redirect_to customer_url, notice: "Your connection to noCRM has been revoked!"
  end

  private

  def customer_params
    params.require(:customer).permit(:nocrm_account, :api_key)
  end

end

app/views/customers/show.html.erb
<div class="container">
  <div class="rounded-3 bg-white shadow-sm p-5 mx-auto my-5">

    <%= image_tag( asset_path("logo.svg"), class: 'mw-100 me-4', width: 200 ) %>

    <hr class="my-4 bg-primary"/>

    <% unless current_customer.has_connected_nocrm? %>
      <p>
        If you don't have a noCRM account yet, create a free trial account here : <%= link_to 'nocrm.io', 'https://www.nocrm.io' %>
      </p>

      <p>
        To connect your noCRM account, you need to enter:
      </p>

      <ul>
        <li class="mb-2">
          <p class="m-0"><b>Your account's subdomain</b></p>
          <p class="m-0"><small class=""><i class="fa-solid fa-circle-info text-success"></i> The part between "https://" and ".nocrm.io" in the address bar of your browser</small></p>
        </li>
        <li class="mb-2">
          <p class="m-0"><b>Your API key</b></p>
          <p class="m-0"><small class=""><i class="fa-solid fa-circle-info text-success"></i> You can create API keys in the admin sections of your account, <%= link_to "more info", "https://www.nocrm.io/help/API" %>.</small></p>
        </li>
      </ul>
      <hr class="my-4 bg-primary"/>
    <% end %>

    <div class="max-w-50">
      <p class="lead">
        <% if current_customer.has_connected_nocrm? %>
          <i class="fa-solid fa-circle-check text-success"></i> Your noCRM account is connected
        <% else %>
          Connect your noCRM account
        <% end %>
      </p>
      <%= form_for current_customer do |f| %>
        <div class="form-floating mb-3">
          <%= f.text_field :nocrm_account, placeholder: 'mycompany', class: 'form-control', required: true, disabled: current_customer.api_key.present? %>
          <%= f.label :nocrm_account, "Your noCRM account's subdomain" %>
        </div>
        <div class="form-floating mb-3">
          <%= f.text_field :api_key, class: 'form-control', required: true, disabled: current_customer.api_key.present?, placeholder: '********************'  %>
          <%= f.label :api_key, "Your noCRM API key" %>
        </div>
        <% unless current_customer.api_key.present? %>
          <%= f.button class: 'btn btn-success', type: :submit do %>
            <span class="show-when-enabled">Save</span>
            <span class="show-when-disabled"><i class="fas fa-spinner fa-spin me-2"></i> Connecting your account and synchronizing data...</span>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="alert alert-primary mt-3 w-auto">
      Webhook events from your noCRM account will be sent at: <br>
      <code><%= NocrmApi.webhook_events_target(current_tenant) %></code>
    </div>
  </div>

    <% if current_customer.has_connected_nocrm? %>
      <div class="d-flex mt-4">
        <%= link_to ping_api_customer_url, class: 'btn btn-primary' do %>
          <i class="fa-solid fa-arrows-rotate me-2"></i>
          Test connection
        <% end %>
        <%= button_to revoke_token_customer_url, method: :post, form: { data: { turbo_confirm: "Are you sure? Revoking the connection will reset all your fields mapping. There is no undo." } }, class: 'btn btn-danger ms-2' do %>
          <i class="fa-solid fa-link-simple-slash me-2"></i>
          Revoke connection
        <% end %>
      </div>
    <% end %>
  </div>
</div>