config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root "mappings#index"

  resources :webhook_events, only: [:create, :index] do
    member do
      put :reprocess
    end
  end

  resource :customer, only: [:show, :update] do
    member do
      post :revoke_token
      get :ping_api
      get :wizard
    end
  end

  resources :mappings, only: [:index]
  resources :nocrm_steps, module: :mappings
  resources :nocrm_field_types, module: :mappings

  # oauth section for salesforce
  namespace :auth do
    resource :salesforce, controller: :salesforce, only: [:show] do
      collection do
        post :synchronize_fields
        post :revoke_token
      end
    end
    resources :salesforce, only: [] do
      collection do
        get :connect
        get :oauth2callback
        get :authentication
      end
    end
  end
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  acts_as_tenant :customer

  enum status: [:pending, :processing, :ok, :error], _prefix: true

  def process!
    status_processing!

    result =
      case data['event']
      when 'lead.creation', 'lead.any_update'
        WebhookEvent::LeadCreatedOrUpdated.new(self).process
      else
        { body: "#{data['event']} is not implemented", status: :error }
      end

    update(result: result[:body], status: result[:status])
  end
end

app/controllers/webhook_events_controller.rb
class WebhookEventsController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate_customer!, only: [:create]
  before_action :authenticate_webhook, only: [:create]

  def create
    data = params[:webhook_event][:data]
    case params[:webhook_event][:event]
    when 'account.step.created'
      NocrmSyncService.create_step(data)
    when 'account.step.updated'
      NocrmSyncService.update_step(data)
    when 'account.step.deleted'
      NocrmSyncService.delete_step(data)
    when 'account.pipeline.updated'
      NocrmSyncService.update_pipeline(data)
    when 'account.default_field.created'
      NocrmSyncService.create_field_type(data)
    when 'account.default_field.updated'
      NocrmSyncService.update_field_type(data)
    when 'account.default_field.deleted'
      NocrmSyncService.delete_field_type(data)
    when 'lead.creation', 'lead.any_update'
      webhook_event = WebhookEvent.create(data: params[:webhook_event])
      webhook_event.process!
    end
    head :ok
  end

  def index
    @webhook_events = WebhookEvent.order(id: :desc).page(params[:page]).per(100)
  end

  def reprocess
    @webhook_event = WebhookEvent.find(params[:id])
    @webhook_event.process!
    render @webhook_event
  end

  private

  def authenticate_webhook
    customer = Customer.find_by(webhooks_token: params[:token])
    if customer && signature_valid?(customer)
      customer.current_tenant!
    else
      head :unauthorized
    end
  end

  def signature_valid?(customer)
    params[:webhook_event][:signature] == Digest::SHA1.hexdigest(params[:webhook_event][:id].to_s + customer.api_key)
  end
end

app/helpers/webhook_events_helper.rb
module WebhookEventsHelper
end

app/views/webhook_events/_webhook_event.html.erb
<%= turbo_frame_tag webhook_event, class: "divTableRow" do %>
  <div class="divTableCell"><%= webhook_event.id %></div>
  <div class="divTableCell">
    <% if webhook_event.status_error? %>
      <div class="w-2 h-2 rounded-circle bg-danger anim-ping ping-danger me-5 flex-shrink-0"></div>
    <% elsif webhook_event.status_pending? %>
      <div class="w-2 h-2 rounded-circle bg-gray me-5 flex-shrink-0"></div>
    <% elsif webhook_event.status_processing? %>
      <div class="w-2 h-2 rounded-circle bg-warning anim-ping ping-warning me-5 flex-shrink-0"></div>
    <% else %>
      <div class="w-2 h-2 rounded-circle bg-success me-5 flex-shrink-0"></div>
    <% end %>
  </div>
  <div class="divTableCell">
    <% webhook_event.result.each do |object_type, result| %>
      <span class="me-2">
        <% fa_icon_css = "fa-circle-check fa-solid text-success" if result['status'] == 'success' %>
        <% fa_icon_css = "fa-empty-set fa-solid text-muted" if result['status'] == 'skipped' %>
        <% fa_icon_css = "fa-circle-exclamation fa-solid text-danger" if result['status'] == 'error' %>
        <i class="fas <%= fa_icon_css %>"></i>
        <%= object_type %>
      </span>
    <% end rescue nil %>
  </div>
  <div class="divTableCell">
    <button type="button" class="btn btn-link fs-7 px-0 text-blue-700 text-decoration-none ms-auto text-nowrap" data-bs-toggle="modal" data-bs-target="#<%= dom_id(webhook_event, 'paramsModal') %>">
      <i class="fas fa-eye me-2"></i>
      See params
    </button>
    <!-- Modal -->
    <div class="modal fade" id="<%= dom_id(webhook_event, 'resultModal') %>" tabindex="-1" aria-labelledby="<%= dom_id(webhook_event, 'resultModal') %>Label" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="<%= dom_id(webhook_event, 'resultModal') %>Label">Webhook Event <%= webhook_event.id %> result</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <code>
              <pre><%= JSON.pretty_generate(webhook_event.result) %></pre>
            </code>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="divTableCell">
    <button type="button" class="btn btn-link fs-7 px-0 text-blue-700 text-decoration-none ms-auto text-nowrap" data-bs-toggle="modal" data-bs-target="#<%= dom_id(webhook_event, 'resultModal') %>">
      <i class="fas fa-eye me-2"></i>
      See result
    </button>
    <!-- Modal -->
    <div class="modal fade" id="<%= dom_id(webhook_event, 'paramsModal') %>" tabindex="-1" aria-labelledby="<%= dom_id(webhook_event, 'paramsModal') %>Label" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="<%= dom_id(webhook_event, 'paramsModal') %>Label">Webhook Event <%= webhook_event.id %> params</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <code>
              <pre><%= JSON.pretty_generate(webhook_event.data) %></pre>
            </code>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= tag.div class: 'divTableCell text-nowrap', data: { controller: "tooltip", tooltip_options_value: { title: webhook_event.updated_at.to_formatted_s(:short) + " UTC" } } do %>
    <%= time_ago_in_words(webhook_event.updated_at) %> ago
  <% end %>
  <div class="divTableCell">
    <% if webhook_event.status_error? %>
      <%= button_to reprocess_webhook_event_path(webhook_event), method: :put, class: "btn btn-danger fs-7 d-flex align-items-center" do %>
        <span class="show-when-enabled"><i class="fas fa-arrows-rotate me-2"></i>Reprocess</span>
        <span class="show-when-disabled"><i class="fas fa-arrows-rotate fa-spin me-2"></i>Reprocessing...</span>
      <% end %>
    <% else %>
      <div class="btn btn-light fs-7 d-inline-flex align-items-center cursor-not-allowed">
        <i class="fas fa-arrows-rotate me-2"></i>Reprocess
      </div>
    <% end %>
  </div>
<% end %>

app/views/webhook_events/index.html.erb
<div class="container pt-4">
  <div class="rounded-3 bg-white shadow-sm p-4 mx-auto my-5">
    <% if @webhook_events.any? %>
      <div class="divTable">
        <div class="divTableHeading">
          <div class="divTableHead">ID</div>
          <div class="divTableHead">Status</div>
          <div class="divTableHead">Response message</div>
          <div class="divTableHead">Params</div>
          <div class="divTableHead">Result</div>
          <div class="divTableHead">Date</div>
          <div class="divTableHead">Actions</div>
        </div>
        <div class="divTableBody">
          <%= render @webhook_events %>
        </div>
      </div>

      <%= paginate @webhook_events %>
    <% else %>
      <div class="p-5 border rounded-3 my-5">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">No logs yet.</h1>
          <p class="col-md-8 fs-5">
            Here you will find the logs of all wehbooks sent by noCRM.
            Logs are useful to monitor data synchronization and understand why some data failed to be synced.
          </p>
          <% if current_customer.has_connected_nocrm? %>
          <p class="col-md-8 fs-5">
            The first logs will appear here when events occur on your noCRM account.
          </p>
          <% else %>
            <%= link_to "Connect noCRM", customer_url, class: 'btn btn-primary btn-lg' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>